### ISSUE TITLE
Error: invalid hexlify value (argument="value", value="", code=INVALID_ARGUMENT, version=bytes/5.7.0)

### ISSUE THREAD

**Issue by BOBseal** [thirdweb-example/nft-gated-website#7]
I cloned the repo and did yarn dev ... this error is showing

error - Error: invalid hexlify value (argument="value", value="", code=INVALID_ARGUMENT, version=bytes/5.7.0)
    at Logger.makeError (T:\smash\smoosh\nft-gated-website\node_modules\@ethersproject\logger\lib\index.js:238:21)
    at Logger.throwError (T:\smash\smoosh\nft-gated-website\node_modules\@ethersproject\logger\lib\index.js:247:20)
    at Logger.throwArgumentError (T:\smash\smoosh\nft-gated-website\node_modules\@ethersproject\logger\lib\index.js:250:21)
    at hexlify (T:\smash\smoosh\nft-gated-website\node_modules\@ethersproject\bytes\lib\index.js:200:19)
    at new SigningKey (T:\smash\smoosh\nft-gated-website\node_modules\@ethersproject\signing-key\lib\index.js:20:82)
    at new Wallet (T:\smash\smoosh\nft-gated-website\node_modules\@ethersproject\wallet\lib\index.js:120:36)
    at Function.fromPrivateKey (T:\smash\smoosh\nft-gated-website\node_modules\@thirdweb-dev\sdk\dist\thirdweb-checkout-cb55a273.cjs.dev.js:16091:20)
    at ThirdwebAuth (webpack-internal:///./node_modules/@thirdweb-dev/auth/next/evm/dist/thirdweb-dev-auth-next-evm.esm.js:121:69)
    at eval (webpack-internal:///./auth.config.js:9:113)
    at Object../auth.config.js (T:\smash\smoosh\nft-gated-website\.next\server\pages\index.js:54:1) {
  reason: 'invalid hexlify value',
  code: 'INVALID_ARGUMENT',
  argument: 'value',
  value: '',
  page: '/'

**Comment by jarrodwatts** [comment]
Please view the README file for instructions on adding your private key

**Comment by BOBseal** [comment]
Nah I made sure I am following every Instructions , from I to the S. I am alo following .env rules, just cloned it, set it up and run dev and it shows this

**Comment by BlockchainDeveloper009** [comment]
> Nah I made sure I am following every Instructions , from I to the S. I am alo following .env rules, just cloned it, set it up and run dev and it shows this

How did you resolve this issue??
